### ISSUE TITLE
reproduce

### ISSUE THREAD

**Issue by UltramanSleepless** [ictnlp/NAST-S2x#2]
Hello! I think this is a very good work, but there are so many route in .sh, I really want to know how prepare the dataset   
CVSS and modify these routes.

**Comment by Paulmzr** [comment]
Hi, thanks for your feedback!

We now offer a tutorial on how to use the provided dataset at this [URL](https://github.com/ictnlp/NAST-S2x/tree/main/preprocessing).

Besides, we added some comments to the paths in the shell scripts for better understanding.

Feel free to contact me if you still have any questions.

**Comment by Paulmzr** [comment]
As no questions followed, I close this issue. If you have any questions later, feel free to reopen it.

**Comment by stylon** [comment]
I like your work and I'm currently also in the process to reproduce. The recipes no longer work out of the box: datasets are hard to resemble as they are no longer available at the original locations and fairseq (your submodule version) is no longer compatible with current python. I can fix some of that myself, but it would be better experience if your work continuous to be reproducible.

Why does prep_fbank.py require reference to CoVoST dataset at all? Isn't CVSS derived from the X-to-EN data of CoVoST2? I'm confused. Could the dependency be avoided if only one directions is needed, e.g. FR-EN? In the publication you seem to use CVSS-C for X-to-EN and MUST-C for EN-to-X. Well, you probably use CoVoST2 X-to-EN data for training that ST direction.
