### ISSUE TITLE
What's the ASR-pretrained encoder do you use?

### ISSUE THREAD

**Issue by karrynest** [ictnlp/NAST-S2x#3]
What's the ASR-pretrained encoder do you use? Could you give an example for "ENCODER_PRETRAINED_PATH"  please?

**Comment by Paulmzr** [comment]
Hi, "ENCODER_PRETRAINED_PATH" can an encoder of a model that uses the same architecture (using linguistic decoder only) but is trained on the ASR task. This is what I used in the experiment. You can pretrain the model using 
```--criterion nat_loss_ngram_glat_asr```, 
```--task nat_speech_to_text_ctc_modified```,  
```--arch nonautoregressive_streaming_speech_transformer_segment_to_segment```.

**Comment by Paulmzr** [comment]
I also add an example pretraining scripts at https://github.com/ictnlp/NAST-S2x/blob/main/train_scripts/pretrain_encoder.sh. Hope it helps.

**Comment by Paulmzr** [comment]
As no questions followed, I close this issue. If you have any questions later, feel free to reopen it.
